Support block volume mode PVC
yunify/qingcloud-csi pull request #195
Opened 2021-11-01 02:44 UTC by dkeven

Signed-off-by: dkeven <keven@kubesphere.io>

**What type of PR is this?**
/kind api-change

**What this PR does / why we need it**:

This PR adds suppport for PVCs whose `volumeMode` is `block`, which is not supported before.

2021-11-01 02:45 UTC, dkeven commented
/cc @stoneshi-yunify @f10atin9

2021-11-01 04:00 UTC, stoneshi-yunify requested changes
see my comments. Make sure new code does not break old FS volume logic.

2021-11-01 04:00 UTC, stoneshi-yunify commented on pkg/disk/rpcserver/nodeserver.go
> +		//#nosec
what's the meaning of this comment?

2021-11-01 04:00 UTC, stoneshi-yunify commented on pkg/disk/rpcserver/nodeserver.go
> +		if err = os.MkdirAll(mountPath, 0750); err != nil {
should be `if err := os.MkdirAll`

2021-11-01 04:00 UTC, stoneshi-yunify commented on pkg/disk/rpcserver/nodeserver.go
> +			klog.Errorf("Failed to close mountPath:%s with error: %v", mountPath, err)
almost all errors in this function were logged. This is not recommended. Should return the error, and let the caller decide whether to log the error.

2021-11-01 04:00 UTC, stoneshi-yunify commented on pkg/disk/rpcserver/controllerserver.go
> +	// If volume is block mode, it doesn't need NodeExpandVolume operation
should be `If volume is in block mode`, and as all followings.

2021-11-01 04:00 UTC, stoneshi-yunify commented on pkg/disk/rpcserver/nodeserver.go
> +	// check if volume exists in the first place
remove `in the first place` as it's a bit misleading,  this is not the first check in this function.

2021-11-01 04:00 UTC, stoneshi-yunify commented on pkg/disk/rpcserver/nodeserver.go
> +	// we skip the staging operation in this case
should just say `skip staging if volume in block mode`

2021-11-01 04:00 UTC, stoneshi-yunify commented on pkg/disk/rpcserver/nodeserver.go
> +	// block mode volume's stats can't be retrieved like that of fs mode ones
should be `... like those filesystem volumes`

2021-11-01 07:15 UTC, dkeven commented
@stoneshi-yunify Thanks for your detailed review, I've updated the code as suggested.

> see my comments. Make sure new code does not break old FS volume logic.

I've tested both the FS and Block mode, and they works correctly.

> what's the meaning of this comment?

Can't reply in the thread as new commit's been force-pushed.

Some linters, like gosec, don't allow creating file whose path is a variable, this comment disables the check.

As we don't do this kind of linting, I think it's okay to remove this comment.

2021-11-04 07:14 UTC, stoneshi-yunify approved these changes
/lgtm

2021-11-04 07:14 UTC, merged